Internal Server Error: /print_invoice/
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\tss\views.py", line 91, in print_invoice
    pisa_status = pisa.CreatePDF(BytesIO(html.encode("UTF-8")), dest=response, link_callback=fetch_resources)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\document.py", line 139, in pisaDocument
    context = pisaStory(
              ^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\document.py", line 75, in pisaStory
    pisaParser(src, context, default_css, xhtml, encoding, xml_output)
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\parser.py", line 823, in pisaParser
    context.parseCSS()
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\context.py", line 684, in parseCSS
    self.css = self.cssParser.parse(self.cssText)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 458, in parse
    src, stylesheet = self._parseStylesheet(src)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 561, in _parseStylesheet
    src, atResults = self._parseAtKeyword(src)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 685, in _parseAtKeyword
    src, result = self._parseAtFontFace(src)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 865, in _parseAtFontFace
    src, properties = self._parseDeclarationGroup(src)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 1101, in _parseDeclarationGroup
    src, single_property = self._parseDeclaration(src)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 1144, in _parseDeclaration
    src, single_property = self._parseDeclarationProperty(src, property_name)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 1152, in _parseDeclarationProperty
    src, expr = self._parseExpression(src)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 1178, in _parseExpression
    src, term2 = self._parseExpressionTerm(src.lstrip())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 1221, in _parseExpressionTerm
    raise self.ParseError(msg, src, ctxsrc)
xhtml2pdf.w3c.cssParser.CSSParseError: Terminal function expression expected closing ')':: ('format(', "'truetype;\n\n        ")
Error while parsing CSS file
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\context.py", line 513, in parseExternal
    result = self.parse(cssFile.getData())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 458, in parse
    src, stylesheet = self._parseStylesheet(src)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 542, in _parseStylesheet
    src = self.re_comment.sub("", src)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
Error while parsing CSS file
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\context.py", line 513, in parseExternal
    result = self.parse(cssFile.getData())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 458, in parse
    src, stylesheet = self._parseStylesheet(src)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 542, in _parseStylesheet
    src = self.re_comment.sub("", src)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
Error while parsing CSS file
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\context.py", line 513, in parseExternal
    result = self.parse(cssFile.getData())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 458, in parse
    src, stylesheet = self._parseStylesheet(src)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 542, in _parseStylesheet
    src = self.re_comment.sub("", src)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
Error while parsing CSS file
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\context.py", line 513, in parseExternal
    result = self.parse(cssFile.getData())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 458, in parse
    src, stylesheet = self._parseStylesheet(src)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\xhtml2pdf\w3c\cssParser.py", line 542, in _parseStylesheet
    src = self.re_comment.sub("", src)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\tss\views.py", line 28, in home
    context = {'user': user}
                       ^^^^
UnboundLocalError: cannot access local variable 'user' where it is not associated with a value
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\tss\views.py", line 23, in home
    context = {'user': user}
                       ^^^^
NameError: name 'user' is not defined
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\tss\views.py", line 23, in home
    context = {'user': user}
                       ^^^^
NameError: name 'user' is not defined
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\tss\views.py", line 28, in home
    context = {'user': user}
                       ^^^^
UnboundLocalError: cannot access local variable 'user' where it is not associated with a value
Internal Server Error: /django-check-seo/
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django_check_seo\views.py", line 34, in get_context_data
    launch_checks.launch_checks(page_stats)
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django_check_seo\checks_list\launch_checks.py", line 60, in launch_checks
    getattr(module[0], "run")(site)
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django_check_seo\checks_list\check_keyword_url.py", line 57, in run
    url_path = urlparse(site.full_url, "/").path
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\AppData\Local\Programs\Python\Python312\Lib\urllib\parse.py", line 394, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\AppData\Local\Programs\Python\Python312\Lib\urllib\parse.py", line 130, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
Internal Server Error: /django-check-seo/
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django_check_seo\views.py", line 34, in get_context_data
    launch_checks.launch_checks(page_stats)
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django_check_seo\checks_list\launch_checks.py", line 60, in launch_checks
    getattr(module[0], "run")(site)
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django_check_seo\checks_list\check_keyword_url.py", line 57, in run
    url_path = urlparse(site.full_url, "/").path
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\AppData\Local\Programs\Python\Python312\Lib\urllib\parse.py", line 394, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\AppData\Local\Programs\Python\Python312\Lib\urllib\parse.py", line 130, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
Internal Server Error: /django-check-seo/
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django_check_seo\views.py", line 34, in get_context_data
    launch_checks.launch_checks(page_stats)
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django_check_seo\checks_list\launch_checks.py", line 60, in launch_checks
    getattr(module[0], "run")(site)
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django_check_seo\checks_list\check_keyword_url.py", line 57, in run
    url_path = urlparse(site.full_url, "/").path
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\AppData\Local\Programs\Python\Python312\Lib\urllib\parse.py", line 394, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\AppData\Local\Programs\Python\Python312\Lib\urllib\parse.py", line 130, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
